server:
  port: 8081
  read-timeout: 60
  write-timeout: 60

app:
  #run-mode:debug/release
  run-mode: debug
  pagesize: 10
  log-path: ../log/debug.log
  identity-key: idname

database:
  type: mysql
  user: root
  password: 123456
  host: 127.0.0.1:3306
  name: hmdp
  table-prefix: tb_

redis:
  addr: 127.0.0.1:6379
  pass: 123321
  db: 0
  timeout: 1000
  expired-time: 3600